# Generated by Django 6.0.6 on 2026-06-13 04:44

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=60)),
                ('modelo', models.CharField(max_length=60)),
                ('anio', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2100)], verbose_name='Año')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio base (USD)')),
                ('imagen_url', models.URLField(blank=True, verbose_name='Imagen (URL)')),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
                'ordering': ['marca', 'modelo'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('dni', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'El DNI debe tener 8 digitos.')], verbose_name='DNI')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('CLIENTE', 'Cliente')], default='CLIENTE', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda', models.CharField(choices=[('USD', 'Dolares (USD)')], default='USD', max_length=3)),
                ('precio_bien', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cuota_inicial_monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cuota_inicial_pct', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('10')), django.core.validators.MaxValueValidator(Decimal('30'))], verbose_name='Cuota inicial (%)')),
                ('cuota_balon_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('30'))], verbose_name='Cuota balon (%)')),
                ('tipo_tasa', models.CharField(choices=[('EFECTIVA', 'Tasa Efectiva Anual (TEA)'), ('NOMINAL', 'Tasa Nominal Anual (TNA)')], default='EFECTIVA', max_length=10)),
                ('valor_tasa', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor de la tasa (%)')),
                ('plazo_meses', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(72)])),
                ('tipo_gracia', models.CharField(choices=[('NINGUNA', 'Ninguna'), ('TOTAL', 'Gracia Total'), ('PARCIAL', 'Gracia Parcial')], default='NINGUNA', max_length=10)),
                ('meses_gracia', models.PositiveIntegerField(default=0)),
                ('tasa_seguro_desgravamen', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Seguro desgravamen (% mensual)')),
                ('tasa_seguro_vehicular', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Seguro vehicular (%)')),
                ('cok', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='COK del usuario (% anual)')),
                ('fecha_inicio', models.DateField()),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='core.vehiculo')),
            ],
            options={
                'verbose_name': 'Prestamo',
                'verbose_name_plural': 'Prestamos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_cuota', models.PositiveIntegerField()),
                ('tipo_periodo', models.CharField(choices=[('GRACIA_TOTAL', 'Gracia Total'), ('GRACIA_PARCIAL', 'Gracia Parcial'), ('ORDINARIO', 'Ordinario'), ('CUOTA_BALON', 'Cuota Balon')], max_length=15)),
                ('fecha_vencimiento', models.DateField()),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interes', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amortizacion', models.DecimalField(decimal_places=2, max_digits=14)),
                ('seguro_desgravamen', models.DecimalField(decimal_places=2, max_digits=14)),
                ('seguro_vehicular', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cuota_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('saldo_final', models.DecimalField(decimal_places=2, max_digits=14)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronograma', to='core.prestamo')),
            ],
            options={
                'verbose_name': 'Cronograma',
                'verbose_name_plural': 'Cronogramas',
                'ordering': ['prestamo', 'nro_cuota'],
                'unique_together': {('prestamo', 'nro_cuota')},
            },
        ),
    ]
