# Generated by Django 6.0.6 on 2026-06-14 02:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_usuario_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='cuota_balon_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('40'))], verbose_name='Cuota balon (%)'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='cuota_inicial_pct',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('40'))], verbose_name='Cuota inicial (%)'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='valor_tasa',
            field=models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('8')), django.core.validators.MaxValueValidator(Decimal('24'))], verbose_name='Valor de la tasa (%)'),
        ),
    ]
