# Generated by Django 6.0.6 on 2026-06-14 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_update_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='imagen_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ruta de imagen (static)'),
        ),
    ]
