# Generated by Django 6.0.6 on 2026-06-14 03:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_seed_imagenes_vehiculos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='valor_tasa',
            field=models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('8')), django.core.validators.MaxValueValidator(Decimal('25'))], verbose_name='Valor de la tasa (%)'),
        ),
    ]
