# Generated by Django 6.0.6 on 2026-06-16 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fix_dni_null'),
        ('core', '0007_update_tea_max_25'),
    ]

    operations = [
    ]
