# Generated by Django 6.0.6 on 2026-06-16 23:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_usar_cloudinary_imagenes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='valor_tasa',
            field=models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor de la tasa (%)'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='imagen_url',
            field=models.URLField(blank=True, verbose_name='Imagen (URL)'),
        ),
    ]
